#!/usr/bin/env bash
# Select a NixOS specialisation boot entry on a host, by title substring.
#
# The boot entry for a specialisation is generated by the parent generation's
# bootloader install (see README.md, "Booting into a NixOS specialisation").
# This picks the *latest* entry whose title contains the submitted string and
# arms it for the next boot (one-shot by default). It does not activate the
# specialisation in place: kernel parameters only apply on a cold boot.
#
# Usage:
#   select-boot-entry.sh <host> <match> [options]
#
#   <host>          ssh target (e.g. brys) of a NixOS host using systemd-boot
#   <match>         case-insensitive substring of the boot entry title, e.g.
#                   "llm-minimal" matches the "NixOS (llm-minimal)" entry
#
# Options:
#   --persist       make it the default entry instead of a one-shot
#   --reboot        reboot the host after arming the entry
#   --list          only list the matching entries, newest first; change nothing
#   --rebuild       run `nixos-rebuild.sh boot remote=<host>` first, so the
#                   entries reflect the current tree (needed for a kernel-param
#                   change to take effect); off by default
#   -h, --help      show this help
#
# Defaults: one-shot selection, no reboot, no rebuild.
set -eEuo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() { sed -n '2,26p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }

host=""
match=""
persist=0
reboot=0
list_only=0
rebuild=0

while test "$#" -gt 0; do
  case "$1" in
  -h | --help)
    usage
    exit 0
    ;;
  --persist) persist=1 ;;
  --reboot) reboot=1 ;;
  --list) list_only=1 ;;
  --rebuild) rebuild=1 ;;
  -*)
    echo "unknown option: $1" >&2
    usage >&2
    exit 2
    ;;
  *)
    if test -z "${host}"; then host="$1"; elif test -z "${match}"; then match="$1"; else
      echo "unexpected argument: $1" >&2
      exit 2
    fi
    ;;
  esac
  shift
done

if test -z "${host}" || test -z "${match}"; then
  usage >&2
  exit 2
fi

if ! command -v jq >/dev/null; then
  echo "select-boot-entry: jq is required" >&2
  exit 1
fi

# shellcheck disable=SC2029  # the remote args are intentionally client-expanded
run_remote() { ssh "${host}" "$@"; }

if test "${rebuild}" = 1; then
  echo "rebuilding ${host} boot entries..."
  "${script_dir}/nixos-rebuild.sh" boot "remote=${host}"
fi

entries="$(run_remote sudo bootctl list --json=short)"

# Latest entry whose title contains the match, by the generation number in the
# `version` field. Sorted descending so the newest comes first.
selected="$(
  jq -r --arg m "${match}" '
    map(select((.title // "") | ascii_downcase | contains($m | ascii_downcase)))
    | map(. + { gen: ((.version | try (capture("Generation (?<g>[0-9]+)").g) catch "0") // "0" | tonumber) })
    | sort_by(.gen) | reverse
    | .[]
    | "\(.id)\t\(.gen)\t\(.title)"
  ' <<<"${entries}"
)"

if test -z "${selected}"; then
  echo "select-boot-entry: no boot entry title contains '${match}' on ${host}" >&2
  exit 1
fi

if test "${list_only}" = 1; then
  printf '%s\n' "${selected}" | awk -F'\t' '{ printf "gen %-6s %s\n        %s\n", $2, $3, $1 }'
  exit 0
fi

entry_id="$(printf '%s\n' "${selected}" | head -n1 | cut -f1)"
entry_title="$(printf '%s\n' "${selected}" | head -n1 | cut -f3)"
entry_gen="$(printf '%s\n' "${selected}" | head -n1 | cut -f2)"

if test "${persist}" = 1; then
  verb=set-default
else
  verb=set-oneshot
fi

run_remote sudo bootctl "${verb}" "${entry_id}"
echo "${verb}: gen ${entry_gen} ${entry_title}"
echo "        ${entry_id}"

if test "${reboot}" = 1; then
  echo "rebooting ${host}..."
  run_remote sudo systemctl reboot || true
  for _ in $(seq 1 40); do
    sleep 5
    if run_remote true 2>/dev/null; then
      echo "${host} is back up"
      run_remote readlink /run/current-system
      break
    fi
  done
fi
