[tool.poetry]
name = "klg"
version = "0.1.0"
description = "An opinionated utility for working with https://klog.jotaen.net/ time-tracking"
authors = ["Krzysztof Nazarewski <3494992+nazarewk@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "klg" }]

[tool.poetry.dependencies]
python = "^3.12"

# HTTP

# CLI
asyncclick = "^8.1.7.2"

# Trio
trio = "^0.27.0"
anyio = "^4.6.2"
async-cache = "^1.1.1"

# Time
pendulum = "^3.0.0"

# Logging
structlog = "^24.4.0" # logging library at https://www.structlog.org/en/stable/getting-started.html
rich = "^13.9.4"  # UX improvement for structlog
dacite = "^1.8.1"
xdg-base-dirs = "^6.0.2"

[tool.poetry.scripts]
"klg" = "klg.cli:main"

# poetry2nix throws: error: attribute 'dev' missing
[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
