[tool.poetry]
name = "klg"
version = "0.1.0"
description = "An opinionated utility for working with https://klog.jotaen.net/ time-tracking"
authors = ["Krzysztof Nazarewski <3494992+nazarewk@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "klg"}]

[tool.poetry.dependencies]
python = "^3.11"

# HTTP

# CLI
asyncclick = "^8.1.3.4"

# Trio
trio = "^0.22"
anyio = "^3.6.2"
async-cache = "^1.1.1"

# Time
pendulum = "^2.1.2"

# Logging
structlog = "^22.1.0" # logging library at https://www.structlog.org/en/stable/getting-started.html
rich = "^12.6.0"  # UX improvement for structlog
dacite = "^1.6.0"
xdg = "^5.1.1"

[tool.poetry.scripts]
"klg" = 'klg.cli:main'

# poetry2nix throws: error: attribute 'dev' missing
[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
