[tool.poetry]
name = "openapi-python-client-cli"
version = "0.1.0"
description = ""
authors = ["Krzysztof Nazarewski <3494992+nazarewk@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.11"
openapi-python-client = "^0.12.1"

[tool.poetry.scripts]
openapi-python-client = "openapi_python_client.cli:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
