// Package cainit drives the CA initialization loop.
//
// It merges the CA graph, sorts it topologically, and for each CA with `keySource = "managed"`
// generates the key, creates the self-signed root or the intermediate, writes the public
// certificate, and SOPS-encrypts the private key. An `external` CA is left alone: its key
// pre-exists and the CLI only reads it. See design § 3 and § 5.2.
//
// Every side effect goes through an interface, so the loop is testable with no `step` binary, no
// `sops` binary and no CA. The test injects the real binaries against a temporary unattended CA.
package cainit

import (
	"fmt"
	"os"
	"path/filepath"

	"kdn-certs/internal/dag"
	"kdn-certs/internal/decl"
	"kdn-certs/internal/smallstep"
)

// Signer generates a key and creates a CA certificate. It is `smallstep.Signer`.
type Signer interface {
	GenerateKey(keyOut string) error
	CreateCA(req smallstep.CARequest) error
}

// Decryptor decrypts a SOPS key file. It is `sops.Decryptor`. An intermediate needs the plaintext
// key of its parent, and every CA key is SOPS-sourced.
type Decryptor interface {
	Decrypt(sopsFile string, dest string) error
}

// Encryptor encrypts a plaintext key to a raw/binary SOPS file. It is `sops.Encryptor`.
type Encryptor interface {
	Encrypt(plainFile string, sopsFile string) error
}

// Deps holds the side-effect implementations and the tree root.
type Deps struct {
	// Root is the tree root the repo-relative `directory` values resolve against.
	Root string
	// Signer generates keys and creates CA certificates.
	Signer Signer
	// Decryptor decrypts the parent key of an intermediate. A root needs no parent.
	Decryptor Decryptor
	// Encryptor SOPS-encrypts a managed CA key.
	Encryptor Encryptor
	// Force regenerates a CA whose certificate already exists.
	Force bool
	// DryRun prints the plan and changes nothing.
	DryRun bool
	// Logf receives one line per action.
	Logf func(format string, args ...any)
}

// Action is one decision the loop made for one CA.
type Action struct {
	// Name is the CA name.
	Name string `json:"name"`
	// Type is `root` or `intermediate`.
	Type string `json:"type"`
	// CommonName is the subject common name.
	CommonName string `json:"commonName"`
	// CertPath is the repo-relative public certificate path.
	CertPath string `json:"certPath"`
	// KeySource is `managed` or `external`.
	KeySource string `json:"keySource"`
	// Reason is why the CA is created, or empty when it is current.
	Reason string `json:"reason"`
}

// Result is the outcome of one loop run.
type Result struct {
	// Actions holds one entry per CA, in topological order.
	Actions []Action
	// Created counts the CAs that were (or would be) created.
	Created int
}

// absPath joins a repo-relative path onto the tree root.
func (d Deps) absPath(rel string) string {
	if filepath.IsAbs(rel) {
		return rel
	}
	return filepath.Join(d.Root, rel)
}

// Run creates every managed CA in topological order.
//
// A CA whose public certificate already exists is skipped, unless `Force` is set. So a second run
// with no change writes nothing, and a root CA is never regenerated by accident.
func Run(cas decl.CAs, deps Deps) (Result, error) {
	out := Result{}

	order, err := dag.Sort(cas)
	if err != nil {
		return out, err
	}

	for _, name := range order {
		ca := cas[name]

		certRel := filepath.Join(ca.Directory, ca.CertFile)
		certAbs := deps.absPath(certRel)
		keyRel := filepath.Join(ca.Directory, ca.KeyFile+".sops")
		keyAbs := deps.absPath(keyRel)

		action := Action{
			Name:       name,
			Type:       ca.Type,
			CommonName: ca.CommonName,
			CertPath:   certRel,
			KeySource:  ca.KeySource,
		}

		if ca.KeySource != "managed" {
			action.Reason = "external key, left alone"
			out.Actions = append(out.Actions, action)
			continue
		}

		if _, err := os.Stat(certAbs); err == nil && !deps.Force {
			action.Reason = "current"
			out.Actions = append(out.Actions, action)
			continue
		}

		action.Reason = "missing"
		if deps.Force {
			action.Reason = "forced"
		}
		out.Actions = append(out.Actions, action)
		out.Created++

		if deps.DryRun {
			deps.Logf("would create CA %s (%s): %s", name, ca.Type, action.Reason)
			continue
		}

		if err := createOne(cas, deps, ca, certAbs, keyAbs); err != nil {
			return out, err
		}
		deps.Logf("created CA %s (%s): %s", name, ca.Type, action.Reason)
	}

	return out, nil
}

// createOne creates one managed CA: key, certificate, public cert, SOPS-encrypted key.
//
// The private key is written plain to a temporary file, SOPS-encrypted next to the public
// certificate, and the temporary file is removed. So no plaintext key survives the call.
func createOne(cas decl.CAs, deps Deps, ca decl.CA, certAbs string, keyAbs string) error {
	if err := os.MkdirAll(filepath.Dir(certAbs), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(certAbs), err)
	}

	tmpDir, err := os.MkdirTemp("", "kdn-certs-ca-")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	keyPlain := filepath.Join(tmpDir, "ca.key")
	if err := deps.Signer.GenerateKey(keyPlain); err != nil {
		return err
	}

	req := smallstep.CARequest{
		CommonName: ca.CommonName,
		Type:       ca.Type,
		KeyPath:    keyPlain,
		CertPath:   certAbs,
	}

	if ca.Type == "intermediate" {
		if ca.Parent == nil || *ca.Parent == "" {
			return fmt.Errorf("intermediate CA %q names no parent", ca.Name)
		}
		parent, ok := cas[*ca.Parent]
		if !ok {
			return fmt.Errorf("CA %q names parent %q, which is not declared", ca.Name, *ca.Parent)
		}
		parentKeyPlain := filepath.Join(tmpDir, "parent.key")
		parentKeySops := deps.absPath(filepath.Join(parent.Directory, parent.KeyFile+".sops"))
		if err := deps.Decryptor.Decrypt(parentKeySops, parentKeyPlain); err != nil {
			return err
		}
		req.ParentCert = deps.absPath(filepath.Join(parent.Directory, parent.CertFile))
		req.ParentKey = parentKeyPlain
	}

	if err := deps.Signer.CreateCA(req); err != nil {
		return err
	}

	// `step` writes the public certificate with a restrictive mode. A committed public certificate
	// is world-readable, so widen it.
	if err := os.Chmod(certAbs, 0o644); err != nil {
		return fmt.Errorf("chmod %s: %w", certAbs, err)
	}

	if err := deps.Encryptor.Encrypt(keyPlain, keyAbs); err != nil {
		return err
	}

	return nil
}
