[tool.poetry]
name = "ss-util"
version = "0.1.0"
description = "helps dumping and restoring secrets using Secret Service"
authors = ["Krzysztof Nazarewski <3494992+nazarewk@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "ss_util"}]

[tool.poetry.dependencies]
python = "^3.11"


click = "^8.1.7"


# Logging
structlog = "^23.1.0" # logging library at https://www.structlog.org/en/stable/getting-started.html
rich = "^13.5.3"  # UX improvement for structlog

# CLI
secretstorage = "^3.3.3"
# should be 41.0.4, but it's not in poetry2nix yet
cryptography = "41.0.1"
[tool.poetry.scripts]
"ss-util" = 'ss_util.cli:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
