[tool.poetry]
name = "yubikey-configure"
version = "0.1.0"
description = "A script to manage YubiKey configuration while storing data in https://www.passwordstore.org/"
authors = ["Krzysztof Nazarewski <3494992+nazarewk@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "yubikey_configure"}]

[tool.poetry.dependencies]
python = "^3.11"

# CLI
click = "^8.1.3"

# Logging
structlog = "^22.1.0" # logging library at https://www.structlog.org/en/stable/getting-started.html
rich = "^12.6.0"  # UX improvement for structlog

[tool.poetry.scripts]
"yubikey-configure" = 'yubikey_configure.cli:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
